# API-Blueprint for fun & profit

## Data Structures

### Customer (object)
A customer

#### Properties 
- `first_name`
- `last_name`
- pets

### Pet (object)
- `name`
- `species`

## Petstore /petstore

### Pets [GET:/pets]

+ Response 200
    + Attributes (array[Pet])

