# API-Blueprint for fun & profit

## Data Structures

### Customer (object)
A customer

#### Properties 
- `first_name`
- `last_name`
- pets

### Pet (object)
- `name`
- `species`

## Pets

### GET /pets

+ Response 200
    + Attributes (array[Pet])

### POST /pets

+ Request
    + Attributes (Pet)

+ Response 200
    + Attributes (array[Pet])
