FORMAT: 1A
HOST: http://localhost:20080

# API-Blueprint for fun & profit

## Pets [/pets]

### GET

+ Response 200

        [{
            id: "7",
            name: "Dobby",
            gender: "Male",
            species: "Hound"
        }]


### POST

+ Request

        {
            name: "Dobby",
            gender: "Male",
            species: "Hound"
        }

+ Response 200
    + Attributes
        + id: 7


